### ISSUE TITLE
Can you share the dataset of SPARE Challenge

### ISSUE THREAD

**Issue by zlbbme** [zhangzhehao95/CNN-MoCo#3]
Dear author,

Could you please share the data set you used for training and testing? Originally, the data set download of the University of Sydney competition is not available, and your network model uses images in the format of.npy suffix. I hope you can share the data set. Thank you so much.

**Comment by zhangzhehao95** [comment]
Hi,

Thanks for reaching out. We used free-breathing CBCT scans collected from our department as training data. I'm sorry but I cannot share this part because of the restriction on healthcare information. 

The SPARE dataset was only used for testing purpose. However, the personal transfer of SPARE dataset can also be a problem considering the size. I think you should be able to download them directly from the [organizer](https://unisyd-my.sharepoint.com/personal/andy_shieh_sydney_edu_au/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fandy%5Fshieh%5Fsydney%5Fedu%5Fau%2FDocuments%2F%21OnlineOnly%2FSPARE) since I just did this recently. I also met some problems for the download. And my suggestion will be that do NOT download the whole dataset by using 'Toggle selection for all items', but enter each folder and download each zip file one by one. This tedious way works for me at least.

Once you get the dataset (projections) and corresponding reconstruction (images), you can use the code by converting all images to npy format. Let me know if you need more help. Good luck.

**Comment by zlbbme** [comment]
Thanks for your reply，I tried to download SPARE dataset one by one .but I got the damaged files and  can't unzip the files correctly.
So I hope to be able to get this public dataset through your path,because I am really interested in this research direction.
I am looking forward to your early reply. Thanks very much.

**Comment by zhangzhehao95** [comment]
Hi,

I'm sorry that separate downloading didn't work for you. However, I'm afraid that I can not help with the re-sharing becuase we don't know whether this is allowed by the organizer. 

I would suggest you to double check that 1) you have downloaded all files for one dataset before unzipping, i.e. ClinicalVarianDatasets.7z.001 -- ClinicalVarianDatasets.7z.021 for the clinical Varian dataset, 2) and each of them is the correct size. I personally also met the damaged files before. I'm not sure why that happened but a simple re-downloading of those files can fix it. If you still have problems with the downloading, directly contacting the SPARE organizer should be an appropriate way. Hope this can help. 

Best
